// export const semanticAccents = ['info', 'positive', 'warning', 'danger']
export const semanticAccents = ['positive']
export const brandAccents = ['primary']
export const accents = ['neutral', ...brandAccents, ...semanticAccents]
export const contrasts = ['neutral', 'vibrant']
export const emphasises = ['major', 'minor']
